---
title: "DC SUD"
author: "Sarah S."
date: "2022-11-18"
output: html_document
---

#set working directory for all following blocks
```{r, setup, include=FALSE}
knitr::opts_knit$set(root.dir = '/Users/paulsheets/Desktop/CMS Data')
```

#load libraries and set up functions
```{r}

#load libraries
library(readxl)
library(stringr)
library(ggplot2)

#load data by loading all excel files in folder to list
setwd(dir = "/Users/paulsheets/Desktop/CMS Data")

#testing data from multiple states
sheetlist <- dir("/Users/paulsheets/Desktop/CMS Data/", recursive=TRUE, full.names=TRUE, pattern="\\.xlsx$")

#set up functions and objects
fillTheBlanks <- function(x, missing=""){
  rle <- rle(as.character(x))
  empty <- which(rle$value==missing)
  rle$values[empty] <- rle$value[empty-1] 
  inverse.rle(rle)
}

NotFancy <- function(l) {
 l <- format(l, scientific = FALSE)
 parse(text=l)
}


data_preprocess <- function(xl_file, txt_file) {
  #' Function for preprocessing the raw excel files
  #'
  #'Inputs:
  #'@param xl_file The path of the excel file you are preprocessing
  #'@param txt_file The corresponding text file of preprocessing parameters
  #'for the excel file
  #'
  #'@return Returns the desired dataframe
  
  
  # Get parameters for the xlsx file you are loading
  params <- read.table(txt_file, sep=',', header = TRUE, strip.white = TRUE)
  # Check that there are not blanks in either the "Variable" or "Values" columns
  try(
    if(sum(params$Variable=='')>0) 
      stop(paste("Empty 'Variable' name detected, please check ",txt_file)
    )
  )
  try(
    if(sum(params$Values=='')>0) 
      stop(paste("Empty 'Value' detected, please check ",txt_file)
      )
  )
    
    
  # Determine which columns to load and their names
  data <- read_excel(xl_file, sheet = params[params$Variable == "sheet_name", 2])
    
  # Combine all row_rm into one list to use
  z <- sapply(
    str_extract_all(
      params[params$Variable == 'row_rm',2], '[0-9.]+'), 
      function(x) as.numeric(x)
  )
  
  q <- c()
  for (j in 1:dim(z)[2]){
    q <- union(q, c(z[1,j]:z[2,j]))
  }
    
  # remove said rows
  data <- data[-q,]
  
  # load in the specified columns and rename them as requested
  rel_cols <- params[!(params$Variable %in% c('row_rm', 'state', 'sheet_name')),]
  data <- data[,as.numeric(rel_cols[,2])]
  # rename the columns of data to match those from the text file
  colnames(data) <- rel_cols[,1]
  
  
  # fill any blank value in the columns
  
  # Fill in metric name
  data$metric_name <- ifelse((is.na(data$metric_name) | data$metric_name == 'blank'), "",data$metric_name)
  data$metric_name <- fillTheBlanks(data$metric_name)
  
  #Fill in metric number
  data$metric_number <- ifelse((is.na(data$metric_number) | data$metric_number == 'blank'), "",data$metric_number)
  data$metric_number <- fillTheBlanks(data$metric_number)
  
  
  
  #n.a. text in reports
  data <- data.frame(lapply(data, function(x) {
    gsub("n.a.", "", x)
  }))
  
  
  #for (j in unique(data$date)){
  #  
  #}
  data$date <- str_replace(data$date, "/21$", "/2021")
  data$date <- str_replace(data$date, "/21-", "/2021-")
  data$date <- str_replace(data$date, "/20$", "/2020")
  data$date <- str_replace(data$date, "/20-", "/2020-")
  data$date <- substr(data$date, 1, 10)
  data$date <- as.Date(data$date, format = "%m/%d/%Y")
  
  # change the data typing of the columns if necessary
  for (j in 1:length(rel_cols[,2])){
    if (rel_cols[j,3] == 'c'){
      data[,j] <- sapply(data[,j], as.character)
    }
    
    if (rel_cols[j,3] == 'f'){
      data[,j] <- sapply(data[,j], as.factor)
    }
    
    if (rel_cols[j,3] == 'n'){
      data[,j] <- sapply(data[,j], as.numeric)
    }
  }
  
  
  # Add the name of the state to the dataframe
  data$state <- params[params$Variable == 'state',2]
  
  return(data)
}

datalist <- c()
```

#New stuff pasted from the Ross tutorial

```{r}
data_dir <- './data'
# Get excel files from data_dir
sheetlist <- dir(data_dir, recursive=TRUE, full.names=TRUE, pattern='\\.xlsx$')
# Make txt file names by substituting .xlsx for .txt
txtlist <- gsub('.xlsx', '.txt', sheetlist)
```

# Iterate through all of the xlxs/txt pairs, calling the `data_preprocess` function on each one
```{r}
datalist <- c()
for(i in 1:length(sheetlist)){
  data <- data_preprocess(sheetlist[i], txtlist[i])
  
  # name preprocessed dataset and add to datalist
  z <- str_sub(sheetlist[i], start= -17)
  #assign(paste(z), data)
  datalist[[i]] = assign(paste(z), data)
}
# Check that it loaded properly
head(datalist[[1]])
```












# for loop: for each spreadsheet in the sheetlist, run the following code, and then save the data in the 'combo' data frame


```{r}

for (i in 1:length(sheetlist)) {
  print(i)
  x <- sheetlist[i] 
  mon_report <- read_excel(x, sheet = "SUD metrics")
  data <- mon_report
  data$state <- str_match(sheetlist[i], pattern = "//\\s*(.*?)\\s*/")[,2] #need here for below subset
  
  #state specific - need to figure out how to add a column to specify the state the data is from, and then select the appropriate rows
  
  #maybe Ross can make this a function??? 
  
  #DC delete unneeded rows and columns
  data <- data[-(c(1:9, 11:13, 88:123)),]
  data <- data[,-c(3:11)]
  
  # NH, KS delete unneeded rows and columns
  #data <- data[-(c(1:9, 11:13, 91:111)),]
  #data <- data[,-c(3:11)]

  
  
  # same for all states - rest of the data processing 
#make column names
  colnames(data) <- (data[1,])
  data <- data[-1,]
  colnames(data)[1] <- "metric_number"
  colnames(data)[2] <- "metric_name"
  colnames(data)[6] <- "numerator_count"
  colnames(data)[5] <-"denominator"
  colnames(data)[7] <- "rate_percent"
  colnames(data)[3] <- "measurement_period"
  colnames(data)[4] <- "date"
  data <- data[,-(ncol(data))] #removing since column names have changed
  data$state <- str_match(sheetlist[1], pattern = "//\\s*(.*?)\\s*/")[,2] #fixing above
  
  
#Fill in metric number
  data$metric_number <- ifelse(is.na(data$metric_number) == TRUE, "blank", 
                               ifelse(data$metric_number == "blank", "", data$metric_number))
  data$metric_number <- fillTheBlanks(data$metric_number)


# Metric names
  data$metric_name <- ifelse(is.na(data$metric_name) == TRUE, "blank", 
                               ifelse(data$metric_name == "blank", "", data$metric_name))
  data$metric_name <- fillTheBlanks(data$metric_name)
  
  #n.a. text in reports
  data <- data.frame(lapply(data, function(x) {
    gsub("n.a.", "", x)
    }))


#change characters to numeric or factor as appropriate
  data[,1:(ncol(data))] <- sapply(data[,1:(ncol(data))],as.character)
  data[,5:(ncol(data))] <- sapply(data[,5:(ncol(data))],as.numeric)
  data[,1:3] <- sapply(data[,1:3],as.factor)

#date
  data$date <- str_replace(data$date, "/21$", "/2021")
  data$date <- str_replace(data$date, "/21-", "/2021-")
  data$date <- str_replace(data$date, "/20$", "/2020")
  data$date <- str_replace(data$date, "/20-", "/2020-")
  data$date <- substr(data$date, 1, 10) 
  data$date <- as.Date(data$date, format = "%m/%d/%Y")
  
  #name cleaned dataset and add to datalist
  z <- str_sub(sheetlist[i], start= -17)
  assign(paste(z), data)
  datalist[[i]] = assign(paste(z), data)
}
```




```{r}
# add all new dataframes to a combined dataframe
combined = data.table::rbindlist(datalist)

combined$measurement_period <- ifelse(combined$metric_number == "15" | combined$metric_number == "16" | combined$metric_number == "17(1)" | combined$metric_number == "17(2)", "Year", combined$measurement_period)
combined$measurement_period <- ifelse(combined$measurement_period == "Quarter", "Month", combined$measurement_period)
combined$metric_number <- ifelse(combined$metric_number == "blank", 1, combined$metric_number)
```


```{r}
#create smaller dataframe to view quarterly trends in total population
visdata <- combined[combined$state == "INSERT STATE HERE",]
visdata <- visdata[,c(1:4, 6)]
visdata[is.na(visdata)] <- "" 
visdata <- na.omit(visdata)
visdata <- visdata[grep("Month", visdata$measurement_period),]

#visualize trends in quarterly metrics
quarter_plot <- ggplot(data = visdata, mapping = aes(x = date, y = as.numeric(numerator_count), color = as.factor(visdata$metric_number))) + geom_point() + facet_wrap(~as.factor(visdata$metric_number), scales = "free") + geom_smooth() + scale_y_continuous(labels=NotFancy)

suppressWarnings(print(quarter_plot))
```


```{r}
#visualize trends in yearly metrics
visdata2 <- combined[combined$state == "INSERT STATE HERE",]
visdata2 <- combined[,c(1:4, 6)]
visdata2[is.na(visdata2)] <- "" 
visdata2 <- na.omit(visdata2)
visdata2 <- visdata2[grep("Year", visdata2$measurement_period),]

#visualize trends in yearly metrics - might be better for analysts to just look through the data in the 'visdata2' dataframe, especially with metrics 15 and 17.
year_plot <- ggplot(data = visdata2, mapping = aes(x = date, y = as.numeric(numerator_count), color = visdata2$metric_number)) + geom_point() + facet_wrap(~visdata2$metric_number, scales = "free") + geom_smooth() + scale_y_continuous(labels=NotFancy)
suppressWarnings(print(year_plot))
```


```{r}
#RATES AND PERCENTAGES (especially for ALOS, metric 36)
visdata3 <- combined[combined$state == "INSERT STATE HERE",]
alosdata <- visdata3[, c(1:4, 7)]
alosdata <- na.omit(alosdata)
rateplot <- ggplot(data = alosdata, mapping = aes(x = date, y = as.numeric(rate_percent), color = alosdata$metric_number)) + geom_point() + facet_wrap(~alosdata$metric_number, scales = "free")

suppressWarnings(print(rateplot))
```



## CHECK POPULATION SUMS

```{r}
combo <- combined[combined$state == "INSERT STATE HERE",]

#check age denominators
combo$sums <- combo[,8] + combo[,11] + combo[,14]
ifelse(combo$sums != combo$denominator, "age denom no", "ok")

# check age numerators
combo$sums <- combo[,9] + combo[,12] + combo[,15]
ifelse(combo$sums != combo$numerator_count, "age num no", "ok") #166 and 167 wrong

# check dual eligible numerators
combo$sums <- combo[,18] + combo[,21]
ifelse(combo$sums != combo$numerator_count, "dual num no", "ok") 

# check pregnant numerators
combo$sums <- combo[,24] + combo[,27]
ifelse(combo$sums != combo$numerator_count, "preg num no", "ok") 

```